package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Batiment generated by hbm2java
 */
@Entity
@Table(name = "batiment", catalog = "bdeics")
public class Batiment implements java.io.Serializable {

	private String codeBat;
	private String libelleBat;
	private String nombreAppartement;
	private Set<Maison> maisons = new HashSet<Maison>(0);

	public Batiment() {
	}

	public Batiment(String codeBat) {
		this.codeBat = codeBat;
	}

	public Batiment(String codeBat, String libelleBat,
			String nombreAppartement, Set<Maison> maisons) {
		this.codeBat = codeBat;
		this.libelleBat = libelleBat;
		this.nombreAppartement = nombreAppartement;
		this.maisons = maisons;
	}

	@Id
	@Column(name = "CODE_BAT", unique = true, nullable = false, length = 20)
	public String getCodeBat() {
		return this.codeBat;
	}

	public void setCodeBat(String codeBat) {
		this.codeBat = codeBat;
	}

	@Column(name = "LIBELLE_BAT", length = 30)
	public String getLibelleBat() {
		return this.libelleBat;
	}

	public void setLibelleBat(String libelleBat) {
		this.libelleBat = libelleBat;
	}

	@Column(name = "NOMBRE_APPARTEMENT", length = 10)
	public String getNombreAppartement() {
		return this.nombreAppartement;
	}

	public void setNombreAppartement(String nombreAppartement) {
		this.nombreAppartement = nombreAppartement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batiment")
	public Set<Maison> getMaisons() {
		return this.maisons;
	}

	public void setMaisons(Set<Maison> maisons) {
		this.maisons = maisons;
	}

}
