package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "bdeics")
public class Client implements java.io.Serializable {

	private String numClt;
	private Commune commune;
	private Nationalite nationalite;
	private Pays pays;
	private Profession profession;
	private Sexe sexe;
	private TypeClient typeClient;
	private Ville ville;
	private String nomClt;
	private String prenomClt;
	private String matriculeClt;
	private Date datenaissClt;
	private String boitePostClt;
	private String numtelClt;
	private String faxClt;
	private String emailClt;
	private String quartierClt;
	private String ndomicileClt;
	private Date datecreaClt;
	private String photoClt;
	private String civiliteClt;
	private String motDePassClt;
	private String loginClt;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);

	public Client() {
	}

	public Client(String numClt, Sexe sexe) {
		this.numClt = numClt;
		this.sexe = sexe;
	}

	public Client(String numClt, Commune commune, Nationalite nationalite,
			Pays pays, Profession profession, Sexe sexe, TypeClient typeClient,
			Ville ville, String nomClt, String prenomClt, String matriculeClt,
			Date datenaissClt, String boitePostClt, String numtelClt,
			String faxClt, String emailClt, String quartierClt,
			String ndomicileClt, Date datecreaClt, String photoClt,
			String civiliteClt, String motDePassClt, String loginClt,
			Set<Contrat> contrats) {
		this.numClt = numClt;
		this.commune = commune;
		this.nationalite = nationalite;
		this.pays = pays;
		this.profession = profession;
		this.sexe = sexe;
		this.typeClient = typeClient;
		this.ville = ville;
		this.nomClt = nomClt;
		this.prenomClt = prenomClt;
		this.matriculeClt = matriculeClt;
		this.datenaissClt = datenaissClt;
		this.boitePostClt = boitePostClt;
		this.numtelClt = numtelClt;
		this.faxClt = faxClt;
		this.emailClt = emailClt;
		this.quartierClt = quartierClt;
		this.ndomicileClt = ndomicileClt;
		this.datecreaClt = datecreaClt;
		this.photoClt = photoClt;
		this.civiliteClt = civiliteClt;
		this.motDePassClt = motDePassClt;
		this.loginClt = loginClt;
		this.contrats = contrats;
	}

	@Id
	@Column(name = "NUM_CLT", unique = true, nullable = false, length = 30)
	public String getNumClt() {
		return this.numClt;
	}

	public void setNumClt(String numClt) {
		this.numClt = numClt;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_COMMUNE")
	public Commune getCommune() {
		return this.commune;
	}

	public void setCommune(Commune commune) {
		this.commune = commune;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_NAT")
	public Nationalite getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(Nationalite nationalite) {
		this.nationalite = nationalite;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PAYS")
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PROFESSION")
	public Profession getProfession() {
		return this.profession;
	}

	public void setProfession(Profession profession) {
		this.profession = profession;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_SEXE", nullable = false)
	public Sexe getSexe() {
		return this.sexe;
	}

	public void setSexe(Sexe sexe) {
		this.sexe = sexe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_TYPECLT")
	public TypeClient getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(TypeClient typeClient) {
		this.typeClient = typeClient;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_VILLE")
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "NOM_CLT", length = 20)
	public String getNomClt() {
		return this.nomClt;
	}

	public void setNomClt(String nomClt) {
		this.nomClt = nomClt;
	}

	@Column(name = "PRENOM_CLT", length = 50)
	public String getPrenomClt() {
		return this.prenomClt;
	}

	public void setPrenomClt(String prenomClt) {
		this.prenomClt = prenomClt;
	}

	@Column(name = "MATRICULE_CLT", length = 30)
	public String getMatriculeClt() {
		return this.matriculeClt;
	}

	public void setMatriculeClt(String matriculeClt) {
		this.matriculeClt = matriculeClt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISS_CLT", length = 10)
	public Date getDatenaissClt() {
		return this.datenaissClt;
	}

	public void setDatenaissClt(Date datenaissClt) {
		this.datenaissClt = datenaissClt;
	}

	@Column(name = "BOITE_POST_CLT", length = 30)
	public String getBoitePostClt() {
		return this.boitePostClt;
	}

	public void setBoitePostClt(String boitePostClt) {
		this.boitePostClt = boitePostClt;
	}

	@Column(name = "NUMTEL_CLT", length = 30)
	public String getNumtelClt() {
		return this.numtelClt;
	}

	public void setNumtelClt(String numtelClt) {
		this.numtelClt = numtelClt;
	}

	@Column(name = "FAX_CLT", length = 30)
	public String getFaxClt() {
		return this.faxClt;
	}

	public void setFaxClt(String faxClt) {
		this.faxClt = faxClt;
	}

	@Column(name = "EMAIL_CLT", length = 30)
	public String getEmailClt() {
		return this.emailClt;
	}

	public void setEmailClt(String emailClt) {
		this.emailClt = emailClt;
	}

	@Column(name = "QUARTIER_CLT", length = 30)
	public String getQuartierClt() {
		return this.quartierClt;
	}

	public void setQuartierClt(String quartierClt) {
		this.quartierClt = quartierClt;
	}

	@Column(name = "NDOMICILE_CLT", length = 30)
	public String getNdomicileClt() {
		return this.ndomicileClt;
	}

	public void setNdomicileClt(String ndomicileClt) {
		this.ndomicileClt = ndomicileClt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREA_CLT", length = 10)
	public Date getDatecreaClt() {
		return this.datecreaClt;
	}

	public void setDatecreaClt(Date datecreaClt) {
		this.datecreaClt = datecreaClt;
	}

	@Column(name = "PHOTO_CLT", length = 10)
	public String getPhotoClt() {
		return this.photoClt;
	}

	public void setPhotoClt(String photoClt) {
		this.photoClt = photoClt;
	}

	@Column(name = "CIVILITE_CLT", length = 10)
	public String getCiviliteClt() {
		return this.civiliteClt;
	}

	public void setCiviliteClt(String civiliteClt) {
		this.civiliteClt = civiliteClt;
	}

	@Column(name = "MOT_DE_PASS_CLT", length = 30)
	public String getMotDePassClt() {
		return this.motDePassClt;
	}

	public void setMotDePassClt(String motDePassClt) {
		this.motDePassClt = motDePassClt;
	}

	@Column(name = "LOGIN_CLT", length = 30)
	public String getLoginClt() {
		return this.loginClt;
	}

	public void setLoginClt(String loginClt) {
		this.loginClt = loginClt;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "client")
	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

}
