package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Commune generated by hbm2java
 */
@Entity
@Table(name = "commune", catalog = "bdeics")
public class Commune implements java.io.Serializable {

	private String codeCommune;
	private String libelleCommune;
	private Set<Client> clients = new HashSet<Client>(0);

	public Commune() {
	}

	public Commune(String codeCommune) {
		this.codeCommune = codeCommune;
	}

	public Commune(String codeCommune, String libelleCommune,
			Set<Client> clients) {
		this.codeCommune = codeCommune;
		this.libelleCommune = libelleCommune;
		this.clients = clients;
	}

	@Id
	@Column(name = "CODE_COMMUNE", unique = true, nullable = false, length = 10)
	public String getCodeCommune() {
		return this.codeCommune;
	}

	public void setCodeCommune(String codeCommune) {
		this.codeCommune = codeCommune;
	}

	@Column(name = "LIBELLE_COMMUNE", length = 30)
	public String getLibelleCommune() {
		return this.libelleCommune;
	}

	public void setLibelleCommune(String libelleCommune) {
		this.libelleCommune = libelleCommune;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commune")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
