package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "bdeics")
public class Contrat implements java.io.Serializable {

	private String codeContrat;
	private Client client;
	private Facture facture;
	private Maison maison;
	private PrototypeMaison prototypeMaison;
	private Utilisateur utilisateur;
	private String etatContrat;
	private Date dateDebutContrat;
	private Date dateFinContrat;
	private Integer qteAcq;
	private BigDecimal coutMtRestant;
	private Set<Maison> maisons = new HashSet<Maison>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Contrat() {
	}

	public Contrat(String codeContrat, Client client, Maison maison,
			PrototypeMaison prototypeMaison, Utilisateur utilisateur) {
		this.codeContrat = codeContrat;
		this.client = client;
		this.maison = maison;
		this.prototypeMaison = prototypeMaison;
		this.utilisateur = utilisateur;
	}

	public Contrat(String codeContrat, Client client, Facture facture,
			Maison maison, PrototypeMaison prototypeMaison,
			Utilisateur utilisateur, String etatContrat, Date dateDebutContrat,
			Date dateFinContrat, Integer qteAcq, BigDecimal coutMtRestant,
			Set<Maison> maisons, Set<Facture> factures) {
		this.codeContrat = codeContrat;
		this.client = client;
		this.facture = facture;
		this.maison = maison;
		this.prototypeMaison = prototypeMaison;
		this.utilisateur = utilisateur;
		this.etatContrat = etatContrat;
		this.dateDebutContrat = dateDebutContrat;
		this.dateFinContrat = dateFinContrat;
		this.qteAcq = qteAcq;
		this.coutMtRestant = coutMtRestant;
		this.maisons = maisons;
		this.factures = factures;
	}

	@Id
	@Column(name = "CODE_CONTRAT", unique = true, nullable = false, length = 30)
	public String getCodeContrat() {
		return this.codeContrat;
	}

	public void setCodeContrat(String codeContrat) {
		this.codeContrat = codeContrat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NUM_CLT", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_FACT")
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_MAIS", nullable = false)
	public Maison getMaison() {
		return this.maison;
	}

	public void setMaison(Maison maison) {
		this.maison = maison;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PROTOTYPE", nullable = false)
	public PrototypeMaison getPrototypeMaison() {
		return this.prototypeMaison;
	}

	public void setPrototypeMaison(PrototypeMaison prototypeMaison) {
		this.prototypeMaison = prototypeMaison;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_UTILISATEUR", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "ETAT_CONTRAT", length = 30)
	public String getEtatContrat() {
		return this.etatContrat;
	}

	public void setEtatContrat(String etatContrat) {
		this.etatContrat = etatContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT_CONTRAT", length = 10)
	public Date getDateDebutContrat() {
		return this.dateDebutContrat;
	}

	public void setDateDebutContrat(Date dateDebutContrat) {
		this.dateDebutContrat = dateDebutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN_CONTRAT", length = 10)
	public Date getDateFinContrat() {
		return this.dateFinContrat;
	}

	public void setDateFinContrat(Date dateFinContrat) {
		this.dateFinContrat = dateFinContrat;
	}

	@Column(name = "QTE_ACQ")
	public Integer getQteAcq() {
		return this.qteAcq;
	}

	public void setQteAcq(Integer qteAcq) {
		this.qteAcq = qteAcq;
	}

	@Column(name = "COUT_MT_RESTANT", precision = 15)
	public BigDecimal getCoutMtRestant() {
		return this.coutMtRestant;
	}

	public void setCoutMtRestant(BigDecimal coutMtRestant) {
		this.coutMtRestant = coutMtRestant;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "contrat")
	public Set<Maison> getMaisons() {
		return this.maisons;
	}

	public void setMaisons(Set<Maison> maisons) {
		this.maisons = maisons;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "contrat")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
