package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "bdeics")
public class Facture implements java.io.Serializable {

	private String codeFact;
	private Contrat contrat;
	private Utilisateur utilisateur;
	private Date dateFact;
	private BigDecimal fraisDossier;
	private BigDecimal montantTtcFact;
	private BigDecimal remiseFact;
	private String libelleFact;
	private BigDecimal apportInitial;
	private String observationFact;
	private String etatFact;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);
	private Set<Versement> versements = new HashSet<Versement>(0);

	public Facture() {
	}

	public Facture(String codeFact, Contrat contrat, Utilisateur utilisateur) {
		this.codeFact = codeFact;
		this.contrat = contrat;
		this.utilisateur = utilisateur;
	}

	public Facture(String codeFact, Contrat contrat, Utilisateur utilisateur,
			Date dateFact, BigDecimal fraisDossier, BigDecimal montantTtcFact,
			BigDecimal remiseFact, String libelleFact,
			BigDecimal apportInitial, String observationFact, String etatFact,
			Set<Contrat> contrats, Set<Versement> versements) {
		this.codeFact = codeFact;
		this.contrat = contrat;
		this.utilisateur = utilisateur;
		this.dateFact = dateFact;
		this.fraisDossier = fraisDossier;
		this.montantTtcFact = montantTtcFact;
		this.remiseFact = remiseFact;
		this.libelleFact = libelleFact;
		this.apportInitial = apportInitial;
		this.observationFact = observationFact;
		this.etatFact = etatFact;
		this.contrats = contrats;
		this.versements = versements;
	}

	@Id
	@Column(name = "CODE_FACT", unique = true, nullable = false, length = 30)
	public String getCodeFact() {
		return this.codeFact;
	}

	public void setCodeFact(String codeFact) {
		this.codeFact = codeFact;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_CONTRAT", nullable = false)
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_UTILISATEUR", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FACT", length = 10)
	public Date getDateFact() {
		return this.dateFact;
	}

	public void setDateFact(Date dateFact) {
		this.dateFact = dateFact;
	}

	@Column(name = "FRAIS_DOSSIER", precision = 15)
	public BigDecimal getFraisDossier() {
		return this.fraisDossier;
	}

	public void setFraisDossier(BigDecimal fraisDossier) {
		this.fraisDossier = fraisDossier;
	}

	@Column(name = "MONTANT_TTC_FACT", precision = 15)
	public BigDecimal getMontantTtcFact() {
		return this.montantTtcFact;
	}

	public void setMontantTtcFact(BigDecimal montantTtcFact) {
		this.montantTtcFact = montantTtcFact;
	}

	@Column(name = "REMISE_FACT", precision = 15)
	public BigDecimal getRemiseFact() {
		return this.remiseFact;
	}

	public void setRemiseFact(BigDecimal remiseFact) {
		this.remiseFact = remiseFact;
	}

	@Column(name = "LIBELLE_FACT", length = 30)
	public String getLibelleFact() {
		return this.libelleFact;
	}

	public void setLibelleFact(String libelleFact) {
		this.libelleFact = libelleFact;
	}

	@Column(name = "APPORT_INITIAL", precision = 15)
	public BigDecimal getApportInitial() {
		return this.apportInitial;
	}

	public void setApportInitial(BigDecimal apportInitial) {
		this.apportInitial = apportInitial;
	}

	@Column(name = "OBSERVATION_FACT", length = 80)
	public String getObservationFact() {
		return this.observationFact;
	}

	public void setObservationFact(String observationFact) {
		this.observationFact = observationFact;
	}

	@Column(name = "ETAT_FACT", length = 30)
	public String getEtatFact() {
		return this.etatFact;
	}

	public void setEtatFact(String etatFact) {
		this.etatFact = etatFact;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "facture")
	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "facture")
	public Set<Versement> getVersements() {
		return this.versements;
	}

	public void setVersements(Set<Versement> versements) {
		this.versements = versements;
	}

}
