package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "bdeics")
public class Image implements java.io.Serializable {

	private String codeImage;
	private Maison maison;
	private PrototypeMaison prototypeMaison;
	private String libelleImage;

	public Image() {
	}

	public Image(String codeImage) {
		this.codeImage = codeImage;
	}

	public Image(String codeImage, Maison maison,
			PrototypeMaison prototypeMaison, String libelleImage) {
		this.codeImage = codeImage;
		this.maison = maison;
		this.prototypeMaison = prototypeMaison;
		this.libelleImage = libelleImage;
	}

	@Id
	@Column(name = "CODE_IMAGE", unique = true, nullable = false, length = 10)
	public String getCodeImage() {
		return this.codeImage;
	}

	public void setCodeImage(String codeImage) {
		this.codeImage = codeImage;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_MAIS")
	public Maison getMaison() {
		return this.maison;
	}

	public void setMaison(Maison maison) {
		this.maison = maison;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PROTOTYPE")
	public PrototypeMaison getPrototypeMaison() {
		return this.prototypeMaison;
	}

	public void setPrototypeMaison(PrototypeMaison prototypeMaison) {
		this.prototypeMaison = prototypeMaison;
	}

	@Column(name = "LIBELLE_IMAGE", length = 30)
	public String getLibelleImage() {
		return this.libelleImage;
	}

	public void setLibelleImage(String libelleImage) {
		this.libelleImage = libelleImage;
	}

}
