package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maison generated by hbm2java
 */
@Entity
@Table(name = "maison", catalog = "bdeics")
public class Maison implements java.io.Serializable {

	private String codeMais;
	private Batiment batiment;
	private Contrat contrat;
	private TypeMaison typeMaison;
	private Utilisateur utilisateur;
	private String dsgMais;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public Maison() {
	}

	public Maison(String codeMais) {
		this.codeMais = codeMais;
	}

	public Maison(String codeMais, Batiment batiment, Contrat contrat,
			TypeMaison typeMaison, Utilisateur utilisateur, String dsgMais,
			Set<Contrat> contrats, Set<Image> images) {
		this.codeMais = codeMais;
		this.batiment = batiment;
		this.contrat = contrat;
		this.typeMaison = typeMaison;
		this.utilisateur = utilisateur;
		this.dsgMais = dsgMais;
		this.contrats = contrats;
		this.images = images;
	}

	@Id
	@Column(name = "CODE_MAIS", unique = true, nullable = false, length = 20)
	public String getCodeMais() {
		return this.codeMais;
	}

	public void setCodeMais(String codeMais) {
		this.codeMais = codeMais;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_BAT")
	public Batiment getBatiment() {
		return this.batiment;
	}

	public void setBatiment(Batiment batiment) {
		this.batiment = batiment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_CONTRAT")
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_TYPMAISON")
	public TypeMaison getTypeMaison() {
		return this.typeMaison;
	}

	public void setTypeMaison(TypeMaison typeMaison) {
		this.typeMaison = typeMaison;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_UTILISATEUR")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "DSG_MAIS", length = 30)
	public String getDsgMais() {
		return this.dsgMais;
	}

	public void setDsgMais(String dsgMais) {
		this.dsgMais = dsgMais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maison")
	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maison")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
