package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nationalite generated by hbm2java
 */
@Entity
@Table(name = "nationalite", catalog = "bdeics")
public class Nationalite implements java.io.Serializable {

	private String codeNat;
	private String libelleNat;
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Nationalite() {
	}

	public Nationalite(String codeNat) {
		this.codeNat = codeNat;
	}

	public Nationalite(String codeNat, String libelleNat, Set<Client> clients,
			Set<Utilisateur> utilisateurs) {
		this.codeNat = codeNat;
		this.libelleNat = libelleNat;
		this.clients = clients;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "CODE_NAT", unique = true, nullable = false, length = 30)
	public String getCodeNat() {
		return this.codeNat;
	}

	public void setCodeNat(String codeNat) {
		this.codeNat = codeNat;
	}

	@Column(name = "LIBELLE_NAT", length = 30)
	public String getLibelleNat() {
		return this.libelleNat;
	}

	public void setLibelleNat(String libelleNat) {
		this.libelleNat = libelleNat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nationalite")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nationalite")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
