package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", catalog = "bdeics")
public class Pays implements java.io.Serializable {

	private String codePays;
	private String libellePays;
	private Set<Client> clients = new HashSet<Client>(0);

	public Pays() {
	}

	public Pays(String codePays) {
		this.codePays = codePays;
	}

	public Pays(String codePays, String libellePays, Set<Client> clients) {
		this.codePays = codePays;
		this.libellePays = libellePays;
		this.clients = clients;
	}

	@Id
	@Column(name = "CODE_PAYS", unique = true, nullable = false, length = 30)
	public String getCodePays() {
		return this.codePays;
	}

	public void setCodePays(String codePays) {
		this.codePays = codePays;
	}

	@Column(name = "LIBELLE_PAYS", length = 30)
	public String getLibellePays() {
		return this.libellePays;
	}

	public void setLibellePays(String libellePays) {
		this.libellePays = libellePays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
