package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", catalog = "bdeics")
public class Profil implements java.io.Serializable {

	private String codeProfil;
	private String libelleProfil;
	private Date dateProfilUtilisateur;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Profil() {
	}

	public Profil(String codeProfil) {
		this.codeProfil = codeProfil;
	}

	public Profil(String codeProfil, String libelleProfil,
			Date dateProfilUtilisateur, Set<Utilisateur> utilisateurs) {
		this.codeProfil = codeProfil;
		this.libelleProfil = libelleProfil;
		this.dateProfilUtilisateur = dateProfilUtilisateur;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "CODE_PROFIL", unique = true, nullable = false, length = 30)
	public String getCodeProfil() {
		return this.codeProfil;
	}

	public void setCodeProfil(String codeProfil) {
		this.codeProfil = codeProfil;
	}

	@Column(name = "LIBELLE_PROFIL", length = 30)
	public String getLibelleProfil() {
		return this.libelleProfil;
	}

	public void setLibelleProfil(String libelleProfil) {
		this.libelleProfil = libelleProfil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PROFIL_UTILISATEUR", length = 10)
	public Date getDateProfilUtilisateur() {
		return this.dateProfilUtilisateur;
	}

	public void setDateProfilUtilisateur(Date dateProfilUtilisateur) {
		this.dateProfilUtilisateur = dateProfilUtilisateur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
