package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profession generated by hbm2java
 */
@Entity
@Table(name = "profession", catalog = "bdeics")
public class Profession implements java.io.Serializable {

	private String codeProfession;
	private String libelleProfession;
	private Set<Client> clients = new HashSet<Client>(0);

	public Profession() {
	}

	public Profession(String codeProfession) {
		this.codeProfession = codeProfession;
	}

	public Profession(String codeProfession, String libelleProfession,
			Set<Client> clients) {
		this.codeProfession = codeProfession;
		this.libelleProfession = libelleProfession;
		this.clients = clients;
	}

	@Id
	@Column(name = "CODE_PROFESSION", unique = true, nullable = false, length = 10)
	public String getCodeProfession() {
		return this.codeProfession;
	}

	public void setCodeProfession(String codeProfession) {
		this.codeProfession = codeProfession;
	}

	@Column(name = "LIBELLE_PROFESSION", length = 30)
	public String getLibelleProfession() {
		return this.libelleProfession;
	}

	public void setLibelleProfession(String libelleProfession) {
		this.libelleProfession = libelleProfession;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profession")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
