package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrototypeMaison generated by hbm2java
 */
@Entity
@Table(name = "prototype_maison", catalog = "bdeics")
public class PrototypeMaison implements java.io.Serializable {

	private String codePrototype;
	private BigDecimal superficiePrototype;
	private String libellePrototype;
	private String localisationPrototype;
	private Integer qteTotPrototype;
	private Integer qteSouscrPrototype;
	private BigDecimal coutTtcPrototype;
	private Set<Contrat> contrats = new HashSet<Contrat>(0);
	private Set<Image> images = new HashSet<Image>(0);

	public PrototypeMaison() {
	}

	public PrototypeMaison(String codePrototype) {
		this.codePrototype = codePrototype;
	}

	public PrototypeMaison(String codePrototype,
			BigDecimal superficiePrototype, String libellePrototype,
			String localisationPrototype, Integer qteTotPrototype,
			Integer qteSouscrPrototype, BigDecimal coutTtcPrototype,
			Set<Contrat> contrats, Set<Image> images) {
		this.codePrototype = codePrototype;
		this.superficiePrototype = superficiePrototype;
		this.libellePrototype = libellePrototype;
		this.localisationPrototype = localisationPrototype;
		this.qteTotPrototype = qteTotPrototype;
		this.qteSouscrPrototype = qteSouscrPrototype;
		this.coutTtcPrototype = coutTtcPrototype;
		this.contrats = contrats;
		this.images = images;
	}

	@Id
	@Column(name = "CODE_PROTOTYPE", unique = true, nullable = false, length = 20)
	public String getCodePrototype() {
		return this.codePrototype;
	}

	public void setCodePrototype(String codePrototype) {
		this.codePrototype = codePrototype;
	}

	@Column(name = "SUPERFICIE_PROTOTYPE", precision = 15)
	public BigDecimal getSuperficiePrototype() {
		return this.superficiePrototype;
	}

	public void setSuperficiePrototype(BigDecimal superficiePrototype) {
		this.superficiePrototype = superficiePrototype;
	}

	@Column(name = "LIBELLE_PROTOTYPE", length = 40)
	public String getLibellePrototype() {
		return this.libellePrototype;
	}

	public void setLibellePrototype(String libellePrototype) {
		this.libellePrototype = libellePrototype;
	}

	@Column(name = "LOCALISATION_PROTOTYPE", length = 50)
	public String getLocalisationPrototype() {
		return this.localisationPrototype;
	}

	public void setLocalisationPrototype(String localisationPrototype) {
		this.localisationPrototype = localisationPrototype;
	}

	@Column(name = "QTE_TOT_PROTOTYPE")
	public Integer getQteTotPrototype() {
		return this.qteTotPrototype;
	}

	public void setQteTotPrototype(Integer qteTotPrototype) {
		this.qteTotPrototype = qteTotPrototype;
	}

	@Column(name = "QTE_SOUSCR_PROTOTYPE")
	public Integer getQteSouscrPrototype() {
		return this.qteSouscrPrototype;
	}

	public void setQteSouscrPrototype(Integer qteSouscrPrototype) {
		this.qteSouscrPrototype = qteSouscrPrototype;
	}

	@Column(name = "COUT_TTC_PROTOTYPE", precision = 15)
	public BigDecimal getCoutTtcPrototype() {
		return this.coutTtcPrototype;
	}

	public void setCoutTtcPrototype(BigDecimal coutTtcPrototype) {
		this.coutTtcPrototype = coutTtcPrototype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prototypeMaison")
	public Set<Contrat> getContrats() {
		return this.contrats;
	}

	public void setContrats(Set<Contrat> contrats) {
		this.contrats = contrats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prototypeMaison")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
