package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeClient generated by hbm2java
 */
@Entity
@Table(name = "type_client", catalog = "bdeics")
public class TypeClient implements java.io.Serializable {

	private String codeTypeclt;
	private String libelleTypeclt;
	private Set<Client> clients = new HashSet<Client>(0);

	public TypeClient() {
	}

	public TypeClient(String codeTypeclt) {
		this.codeTypeclt = codeTypeclt;
	}

	public TypeClient(String codeTypeclt, String libelleTypeclt,
			Set<Client> clients) {
		this.codeTypeclt = codeTypeclt;
		this.libelleTypeclt = libelleTypeclt;
		this.clients = clients;
	}

	@Id
	@Column(name = "CODE_TYPECLT", unique = true, nullable = false, length = 10)
	public String getCodeTypeclt() {
		return this.codeTypeclt;
	}

	public void setCodeTypeclt(String codeTypeclt) {
		this.codeTypeclt = codeTypeclt;
	}

	@Column(name = "LIBELLE_TYPECLT", length = 30)
	public String getLibelleTypeclt() {
		return this.libelleTypeclt;
	}

	public void setLibelleTypeclt(String libelleTypeclt) {
		this.libelleTypeclt = libelleTypeclt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeClient")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
