package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeMaison generated by hbm2java
 */
@Entity
@Table(name = "type_maison", catalog = "bdeics")
public class TypeMaison implements java.io.Serializable {

	private String codeTypmaison;
	private String libelleTypmaison;
	private Set<Maison> maisons = new HashSet<Maison>(0);

	public TypeMaison() {
	}

	public TypeMaison(String codeTypmaison) {
		this.codeTypmaison = codeTypmaison;
	}

	public TypeMaison(String codeTypmaison, String libelleTypmaison,
			Set<Maison> maisons) {
		this.codeTypmaison = codeTypmaison;
		this.libelleTypmaison = libelleTypmaison;
		this.maisons = maisons;
	}

	@Id
	@Column(name = "CODE_TYPMAISON", unique = true, nullable = false, length = 20)
	public String getCodeTypmaison() {
		return this.codeTypmaison;
	}

	public void setCodeTypmaison(String codeTypmaison) {
		this.codeTypmaison = codeTypmaison;
	}

	@Column(name = "LIBELLE_TYPMAISON", length = 30)
	public String getLibelleTypmaison() {
		return this.libelleTypmaison;
	}

	public void setLibelleTypmaison(String libelleTypmaison) {
		this.libelleTypmaison = libelleTypmaison;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "typeMaison")
	public Set<Maison> getMaisons() {
		return this.maisons;
	}

	public void setMaisons(Set<Maison> maisons) {
		this.maisons = maisons;
	}

}
