package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Versement generated by hbm2java
 */
@Entity
@Table(name = "versement", catalog = "bdeics")
public class Versement implements java.io.Serializable {

	private String codeVers;
	private Facture facture;
	private Utilisateur utilisateur;
	private String etatVers;
	private Date dateVers;
	private String nchequeVers;
	private String typeVers;
	private BigDecimal montantVers;
	private String numborderoVers;
	private String banqueVers;

	public Versement() {
	}

	public Versement(String codeVers, Facture facture, Utilisateur utilisateur) {
		this.codeVers = codeVers;
		this.facture = facture;
		this.utilisateur = utilisateur;
	}

	public Versement(String codeVers, Facture facture, Utilisateur utilisateur,
			String etatVers, Date dateVers, String nchequeVers,
			String typeVers, BigDecimal montantVers, String numborderoVers,
			String banqueVers) {
		this.codeVers = codeVers;
		this.facture = facture;
		this.utilisateur = utilisateur;
		this.etatVers = etatVers;
		this.dateVers = dateVers;
		this.nchequeVers = nchequeVers;
		this.typeVers = typeVers;
		this.montantVers = montantVers;
		this.numborderoVers = numborderoVers;
		this.banqueVers = banqueVers;
	}

	@Id
	@Column(name = "CODE_VERS", unique = true, nullable = false, length = 30)
	public String getCodeVers() {
		return this.codeVers;
	}

	public void setCodeVers(String codeVers) {
		this.codeVers = codeVers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_FACT", nullable = false)
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_UTILISATEUR", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "ETAT_VERS", length = 30)
	public String getEtatVers() {
		return this.etatVers;
	}

	public void setEtatVers(String etatVers) {
		this.etatVers = etatVers;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_VERS", length = 10)
	public Date getDateVers() {
		return this.dateVers;
	}

	public void setDateVers(Date dateVers) {
		this.dateVers = dateVers;
	}

	@Column(name = "NCHEQUE_VERS", length = 30)
	public String getNchequeVers() {
		return this.nchequeVers;
	}

	public void setNchequeVers(String nchequeVers) {
		this.nchequeVers = nchequeVers;
	}

	@Column(name = "TYPE_VERS", length = 30)
	public String getTypeVers() {
		return this.typeVers;
	}

	public void setTypeVers(String typeVers) {
		this.typeVers = typeVers;
	}

	@Column(name = "MONTANT_VERS", precision = 15)
	public BigDecimal getMontantVers() {
		return this.montantVers;
	}

	public void setMontantVers(BigDecimal montantVers) {
		this.montantVers = montantVers;
	}

	@Column(name = "NUMBORDERO_VERS", length = 40)
	public String getNumborderoVers() {
		return this.numborderoVers;
	}

	public void setNumborderoVers(String numborderoVers) {
		this.numborderoVers = numborderoVers;
	}

	@Column(name = "BANQUE_VERS", length = 30)
	public String getBanqueVers() {
		return this.banqueVers;
	}

	public void setBanqueVers(String banqueVers) {
		this.banqueVers = banqueVers;
	}

}
