package com.gestion.model;

// Generated 8 avr. 2016 23:58:01 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville", catalog = "bdeics")
public class Ville implements java.io.Serializable {

	private String codeVille;
	private String libelleVille;
	private Set<Client> clients = new HashSet<Client>(0);

	public Ville() {
	}

	public Ville(String codeVille) {
		this.codeVille = codeVille;
	}

	public Ville(String codeVille, String libelleVille, Set<Client> clients) {
		this.codeVille = codeVille;
		this.libelleVille = libelleVille;
		this.clients = clients;
	}

	@Id
	@Column(name = "CODE_VILLE", unique = true, nullable = false, length = 10)
	public String getCodeVille() {
		return this.codeVille;
	}

	public void setCodeVille(String codeVille) {
		this.codeVille = codeVille;
	}

	@Column(name = "LIBELLE_VILLE", length = 30)
	public String getLibelleVille() {
		return this.libelleVille;
	}

	public void setLibelleVille(String libelleVille) {
		this.libelleVille = libelleVille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
